### ISSUE TITLE
Handling expired tokens

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-authentication#25]
In the [middleware that checks the Authorization header](https://github.com/feathersjs/feathers-authentication/blob/master/src/index.js#L100), if the token is expired we are currently sending back a `401 Unauthorized` response.  I don't think that should be handled here.  If it's an unprotected resource that doesn't require auth, shouldn't we treat it the same as if it were some anonymous user?  I think that a `requireAuth` hook should probably handle whether or not that request is rejected.  Any thoughts otherwise?

**Comment by marshallswain** [comment]
I'm going to fix this so that all authorization is handled through hooks.  When an expired token is provided it will allow the request to go through as it would for an anonymous user instead of punishing those who have expired tokens.

**Comment by ekryski** [comment]
At first I wasn't sure but I think I know what you are getting at here. In the `decoupling` branch I've moved this to a hook called `verifyToken` that can be registered as opposed to blanket middleware. It is currently registered as a before hook on the `/auth/token` service.

My question though now that I think about is, we probably want to always check to see if there is a token (like you were doing) and attempt to validate it only if it is there. Otherwise just move on to the next hook.

The reason being is that the end user would use `req.user` in middleware or `params.user` in hooks to do any authorization but because we aren't using sessions you need to "authenticate" the user on every request.

So my proposal is actually that we have middleware that fires before any other, that attempts to authenticate the user if a token was passed in, otherwise it just moves on through.

**Comment by marshallswain** [comment]
That makes sense to me.  We can use a `decodeToken` hook that does only that, then use the `requireAuth`- or `requireAuthForPrivate`-type hooks to control access.

**Comment by ekryski** [comment]
Ya that what I was thinking but `decodeToken` would be middleware that is applied to **any** route. Basically global middleware, otherwise we'd have to explicitly add a `decodeToken` hook to each service the developer wants to protect.

Now that I type that out, maybe that's not such a big deal???

**Comment by marshallswain** [comment]
Yeah.  It's not a big deal to do
```
service.before({
  all: [
    hooks.auth.decodeToken(), 
    hooks.auth.requireAuth()
  ]
});
```
I think having it be explicit, and not automatic, will be more helpful in the long run.

**Comment by ekryski** [comment]
k :+1:. That's makes it super easy then. If that's the case then we could just use:

```js
service.before({
  all: [authHooks.verifyToken()]
```

You wouldn't even need the `requireAuth` call.

**Comment by marshallswain** [comment]
That works.  Then `decodeToken` would only be needed if you want to implement some kind of custom access control logic, then.

**Comment by ekryski** [comment]
Alrighty, so this is how this works now...

```js
messageService.before({
  all: [
    authHooks.verifyToken({secret: 'feathers-rocks'}),
    authHooks.populateUser(),
    authHooks.requireAuth()
  ]
});
````

We can't rely on just using the `req.feathers.user` middleware hack because we aren't using sessions. So we need to decode the token, populate the user from the user `id` stored in the token payload and then check `hook.params.user`. This should work well for when we do introduce sessions because then it won't matter which way the user authenticates.

**Comment by marshallswain** [comment]
Looks really good!
