### ISSUE TITLE
Allow the authenticate hook to be called with no parameters

### ISSUE THREAD

**Issue by hubgit** [feathersjs/feathers-authentication#473]
After I've configured an app to use `local` and `jwt` strategies, I'd like to be able to call `auth.hooks.authenticate()` as a `before` hook, with no parameters, and have it use the registered strategies by default.

That would make use of the hook more straightforward, unless there's a reason not to allow the `local` strategy in places where you would otherwise call `auth.hooks.authenticate(['jwt'])`?

**Comment by ekryski** [comment]
Nope sorry. We want to keep the strategies you specify explicit. For 3 reasons:

1. So that it is clear which auth which strategies protect which services or plain old express middleware; and
2. because you could have different combinations of auth strategies based for different services; and
3. You can override your default options you configured the strategy with when you register the `authenticate` hook or middleware.

Thanks for the suggestion though! 😄
