### ISSUE TITLE
[Feature Request] Cloud DB's

### ISSUE THREAD

**Issue by flyboarder** [feathersjs/feathers-authentication#581]
Add support for google datastore and azure cosmos db

**Comment by daffl** [comment]
As much as we'd like to support all the databases, this will have to be a community effort. There is a [Feathers plugin generator](https://github.com/feathersjs/generator-feathers-plugin/) and [feathers-memory](https://github.com/feathersjs/feathers-memory) as well as the [feathers-service-tests](https://github.com/feathersjs/feathers-service-tests) and - since it is probably very similar - [feathers-elasticsearch](https://github.com/feathersjs/feathers-elasticsearch) are a good place to get started.
