### ISSUE TITLE
Support multiple auth providers

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-authentication#6]
Based on the options available in the feathers-generator, these are the ones we'll be targeting first:
 - [x] Local
 - [ ] Google
 - [ ] Facebook
 - [x] ~~Twitter~~ - Not making the cut for 1.0 because OAuth1 and OAuth1a require sessions 
 - [ ] Github

This will require changing the local auth to have a keyed config like
```js
auth: {
  secret: 'master-token-generation-secret',
  local: {
    loginEndpoint: '/login'
  },
  facebook: {
    appId: '149b0wv1n4v4',
    secretKey: '1g444g209n'
  },
  twitter: {
    appId: '240v9ndsvn23',
    secretKey: '1g444g209n'
  }
}
```

**Comment by ekryski** [comment]
I've started work on this in the `decoupling` branch. It follows the same config as you outlined above with the exception that we also have a `token` config value. This is because all the auth mechanisms have been broken out into their own services.

The trickier part has been getting twitter to work. Using the https://github.com/drudge/passport-twitter-token module I'm unsure where to get the `oauth_token_secret` and `user_id` using the "reverse auth" mechanism.

**Comment by ekryski** [comment]
So I've got Facebook and Github working. Just working on making it generic for any oAuth2 provider.

Twitter will need to be revisited because it requires a session unless we do one of their different token based methods for authentication. https://dev.twitter.com/oauth

**Comment by ekryski** [comment]
Now that I've done work on this I'd like to split this into a couple issues to better track progress because we aren't doing things that are provider specific but instead are mechanism specific.

Now moving to issues #40, #41, #42 and #43.
